cse370/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("restaurant.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path('admin_home',views.admin_home,name='admin_home'),
    path('sales_history',views.sales_history,name='sales_history'),
    path('add_to_cart/<int:item_id>', views.add_to_cart, name='add_to_cart'),
    path('confirm_order',views.confirm_order,name = 'confirm_order'),
    path('place_order',views.place_order,name='place_order'),
    path('change_status',views.change_status,name='change_status'),
    path('manage_menu',views.manage_menu,name='manage_menu'),
    path('update_item',views.update_item,name='update_item'),
    path('add_item',views.add_item,name='add_item'),
    path('remove_item/<int:item_id>',views.remove_item,name='remove_item'),
    path('my_orders',views.user_orders,name='user_orders'),
    path('configure',views.configure,name='configure'),
    path('remove_menu_item/<int:item_id>',views.remove_menu_item,name='remove_menu_item')
 
]

restaurant/models.py
from django.db import models
import datetime

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=13,null = True)
    is_admin = models.BooleanField(default=False)

class Menu(models.Model):
    item_name = models.CharField(max_length=30)
    price = models.DecimalField(decimal_places=2,max_digits=6)
    description = models.TextField()
    image = models.ImageField(upload_to='media/')

    def __str__(self):
        return f"{self.item_name}"


class Order(models.Model):
    made_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name="orders")
    status = models.CharField(default = "placing",max_length=30)
    created_at = models.DateTimeField(null=True)
    menu_items = models.ManyToManyField(Menu,through='OrderItem')
    grand_total = models.DecimalField(decimal_places=2,max_digits=10,default=0)
    payment_method = models.CharField(max_length=30,default='cash')
    
    def calculate_grand_total(self):
        return sum(item.subtotal for item in self.order_items.all())

    def __str__(self):
        return f"Order #{self.id}, by {self.made_by}"
    
    

class ShippingDetails(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE,related_name="shipping_address")
    houseNo = models.CharField(max_length=10)
    flatNo = models.CharField(max_length=10)
    street =  models.CharField(max_length=30)
    additional = models.CharField(max_length=30,default=None,null=True)

    def __str__(self):
        return  f"""House #{self.houseNo} , Flat #{self.flatNo}
{self.street}

Additional Instructions: {self.additional}"""

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE,related_name="order_items")
    menu_item = models.ForeignKey(Menu, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)  
    subtotal = models.DecimalField(decimal_places=2, max_digits=8,default=0)

    def save(self, *args, **kwargs):
        self.subtotal = self.menu_item.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.menu_item} ( x{self.quantity} )"

class Configuration(models.Model):
    title = models.CharField(max_length=30,default=None)
    logo = models.ImageField(upload_to='media/',default = None)

restaurant/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import * 
import datetime
from django import forms 
from django.contrib.auth.decorators import user_passes_test
# Create your views here.


    

def configure(request):
    if request.method == "POST":
        if Configuration.objects.first():
            restaurant = Configuration.objects.first()
            restaurant.title =  request.POST['restaurant_name'] 
            restaurant.logo = request.FILES.get('logo')
        else:
            restaurant = Configuration(title = request.POST['restaurant_name'],logo=request.FILES.get('logo'))
        restaurant.save()
        
        
    return render(request,"restaurant/configure.html")

def is_admin(user):
    return user.is_authenticated and user.is_admin

def index(request):
    

    
    return render(request,"restaurant/index.html",{
        'user':request.user,
        'menu_items' : Menu.objects.all(),
       
        
        
        })
    


def login_view(request):
    if request.method == "POST":

        
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
       
        if user is not None: 
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "restaurant/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "restaurant/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        phone_number = request.POST['phone_number']
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "restaurant/register.html", {
                "message": "Passwords must match."
            })

        try:
            user = CustomUser.objects.create_user(username, email, password,first_name=first_name,last_name=last_name,phone_number=phone_number)
            user.save()
        except IntegrityError:
            return render(request, "restaurant/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "restaurant/register.html")


def add_to_cart(request, item_id):
    if request.method == 'POST':
        menu_item = Menu.objects.get(pk=item_id)
        placing_orders_exist = Order.objects.filter(made_by=request.user, status='placing').exists()
        if placing_orders_exist:
            order = Order.objects.filter(made_by=request.user, status='placing').last()
        else:
            order = Order(made_by=request.user)
            order.save()
        
    if order:
        try:
            order_item = OrderItem.objects.get(order=order.id, menu_item=menu_item)
            order_item.quantity += 1
            order_item.save()
        except OrderItem.DoesNotExist:
            order_item = OrderItem.objects.create(order=order, menu_item=menu_item, quantity=1)
 
    order.grand_total = order.calculate_grand_total()
    order.save()
    return render(request,"restaurant/index.html",{
        'user':request.user,
        'menu_items' : Menu.objects.all(),
        'order':order,
        'order_items' :OrderItem.objects.filter(order=order),
        
        })
def remove_item(request,item_id):
    order_item = OrderItem.objects.get(pk=item_id)
    order = order_item.order
    order_item.delete()
    return render(request,"restaurant/index.html",{
        'user':request.user,
        'menu_items' : Menu.objects.all(),
        'order':order,
        'order_items' :OrderItem.objects.filter(order=order),
        
        })
def confirm_order(request):
    
    if request.method == "POST":
        order = Order.objects.get(pk=request.POST['order_id'])

        order.save()
        return render(request,"restaurant/index.html",{
        'user':request.user,
        'menu_items' : Menu.objects.all(),
        'order':order,
        'order_items' :OrderItem.objects.filter(order=order),
        'confirm' : True
        
        })

def place_order(request):
    
    if request.method == "POST":
        order = Order.objects.get(pk=request.POST['order_id'])
        order.status = "placed"
        order.created_at = datetime.datetime.now()
        payment_method = request.POST['paymentMethod']
        order.payment_method = payment_method
        order.save()

        houseNo = request.POST.get('houseNo',False)
        flatNo = request.POST.get('flatNo',False)
        street = request.POST.get('streetAddress',False)
        additional = request.POST.get('additional',False)

        address = ShippingDetails(order=order,houseNo = houseNo,flatNo = flatNo,street=street,additional=additional)
        address.save()

        return render(request, "restaurant/index.html",{
        'user':request.user,
        'menu_items' : Menu.objects.all(),
        'order':order,
        'order_items' :OrderItem.objects.filter(order=order),
        'confirm' : True,
        'placed' : True,
        
        })

def user_orders(request):
    return render(request,"restaurant/user_orders.html" , {
                      "orders":Order.objects.filter(made_by=request.user)}
                  )
@user_passes_test(is_admin)
def admin_home(request):
    return render(request,"restaurant/admin_home.html",{"orders":Order.objects.filter(status__in=['placed','Preparing','Dispatched'])})
@user_passes_test(is_admin)
def change_status(request):
    if request.method == "POST":
        status = request.POST['change_status'] 
        order = Order.objects.get(pk=request.POST['order_id'])
        order.status = status
        order.save()
        return render(request,"restaurant/admin_home.html",{"orders":Order.objects.filter(status__in=['placed','Preparing','Dispatched'])})
@user_passes_test(is_admin)
def manage_menu(request):
    menu_items = Menu.objects.all()
    

    return render(request, 'restaurant/manage_menu.html', {'menu_items': menu_items})


@user_passes_test(is_admin)
def update_item(request):
    if request.method == "POST":
        item = Menu.objects.get(pk=request.POST['item_id'])
        item.item_name = request.POST['item_name']
        item.price = request.POST['item_price']
        item.description = request.POST['item_description']

        if request.FILES.get('item_img'):
            item.image = request.FILES.get('item_img')
        
        item.save()

        return render(request, 'restaurant/manage_menu.html', {'menu_items': Menu.objects.all()})
    
    
@user_passes_test(is_admin)
def add_item(request):
    if request.method == "POST":
        item_name= request.POST['item_name']
        item_price=request.POST['item_price']
        description=request.POST['description']
        item_img = request.FILES.get('item_img')

        new_item = Menu(item_name=item_name,price=item_price,description=description,image=item_img)
        new_item.save()
   
    return render(request,'restaurant/add_item.html')

@user_passes_test(is_admin)
def sales_history(request):
    return render(request,"restaurant/sales_history.html",{
        "orders":Order.objects.filter(status= "Delivered")
    })


def remove_item(request,item_id):
    order_item = OrderItem.objects.get(pk=item_id)
    order = order_item.order
    order_item.delete()
    return render(request,"restaurant/index.html",{
        'user':request.user,
        'menu_items' : Menu.objects.all(),
        'order':order,
        'order_items' :OrderItem.objects.filter(order=order),
        
        })

@user_passes_test(is_admin)
def remove_menu_item(request,item_id):
    menu_item = Menu.objects.get(pk=item_id)
    menu_item.delete()
 
    return render(request,"restaurant/manage_menu.html",
            {'menu_items':  Menu.objects.all()})
                  

restaurant/templates/restaurant/add_item.html
{% extends 'restaurant/admin_layout.html' %}

{% block title %}Add a New Item{% endblock %}

{% block content %}
    <div id="main-content">
        <div>
        <div id="item_add">
            <h2>Add a new menu item</h2>
            <div class = "item-data">
                <form method="post" action="{% url 'add_item' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <label for="item_name">Item Name:</label>
                    <input type="text" name="item_name" id="item_name" required>
                    <br>
                    
                    <label for="item_price">Item Price:</label>
                    <input type="text" name="item_price" id="item_price" required>
                    <br>
                    
                    <label for="description">Description:</label>
                    <textarea type="text" name="description" id="description" required></textarea>
                    <br>

                    <label for="item_img">Item Image</label>
                    <input type="file" name="item_img" id="item_img" required>
                    <br>
                    
                

                    <button type="submit">Add</button>
                </form>
        </div>
            
            
     

        </div>
    
    </div>
    </div>
{% endblock %}

restaurant/templates/restaurant/admin_home.html
{% extends 'restaurant/admin_layout.html' %}

{% block title %}Admin Home{% endblock %}

{% block content %}
<div class="order-container">
    <h2>Active Orders</h2>
    {% for order in orders %}
    
        <div class="order-card">
            <div class = 'order-section'>
                <b>Order # {{order.id}}</b>
                <br style = "margin: 10px;">
                {{order.created_at}}
                <br style = "margin: 10px;">

                <b>Payment Method: {{order.payment_method.capitalize}}</b> 
                <br style = "margin: 20px;">
                
                <br style = "margin: 10px;">
            <form method = "post" action ="{%url 'change_status'%}">
                {% csrf_token %}

                <input type = "hidden" name = "order_id" value = {{order.id}}>
                <select id="change_status" name="change_status">
                    <option value="Preparing">Preparing</option>
                    <option value="Dispatched">Dispatched</option>
                    <option value="Delivered">Delivered</option>
                
            
                </select>

                <div class="button-container">
                    <input type="submit" class="change-status-btn" value="Change Status">
                </div>
                
          </form>

            </div>

            <div class = 'order-section'>
            <b>{{order.made_by}}</b>
                <br style = "margin: 10px;">
                
                <b>House # {{order.shipping_address.all.0.houseNo}} Flat# {{order.shipping_address.all.0.flatNo}} </b>
                <br style = "margin: 10px;">
                <b>Street Address: {{order.shipping_address.all.0.street}} </b> 
                <br style = "margin: 10px;">

                {% if order.shipping_address.all.0.additional  %}
                    <br style = "margin: 10px;">
                    <b>Additional Instructions:  {{order.shipping_address.all.0.additional}}</b>
                {%endif%}
            </div>

            <div class = 'order-section'>
                <b>Items</b>
                <br style = "margin: 10px;">
                {% for each in order.order_items.all %}
                    {{each}}
                <br>
                
                {%endfor%}
                <br>
                <b>Grand Total:</b>
            </div>

            <div class = 'order-section'>
                <b>Price</b>
                <br style = "margin: 10px;">
                {% for each in order.order_items.all %}
                    {{each.subtotal}}
                <br>
                {%endfor%}

                <br>

                <b>{{order.grand_total}}</b>
            </div>
        </div>
    {% endfor %}
</div>
   
    

   
    
    
{% endblock %}

restaurant/templates/restaurant/admin_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{restaurant.title}} Admin{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'restaurant/admin_styles.css' %}">
</head>
<body>
    <div id="header">
        <img src = "{{restaurant.logo.url}}" id = "main-logo">
        {%if restaurant.title %}
            <h1>{{restaurant.title}} Dashboard</h1>
        {%else%}
            <h1>Admin Dashboard</h1>
        {%endif%}
    <div id = "header-links">
        <a href="{% url 'admin_home' %}">Dashboard</a> 
        {% if user.is_authenticated %}
         |  Signed in as {{ user.username }} | <a href="{% url 'logout' %}">Logout</a>

        {% else %}
            <a href="{% url 'login' %}">Login as admin</a> 
        {% endif %}   
    </div>  
    </div>

    <div id="main-content">
        {% block content %}
        {% endblock %}   
        <div class="settings">
            <h1>Settings</h1>
            <a href="{% url 'configure' %}" class="big-card">Configure Restaurant</a>
            <br>
            <a href="{% url 'index' %}" class="big-card">FrontPage</a>
            <br>
            <a href="{% url 'admin_home' %}" class="big-card">Admin Dashboard</a>
            <br>
            <a href="{% url 'manage_menu' %}" class="big-card">Manage Menu</a>
            <br>
            <a href="{% url 'add_item' %}" class="big-card">Add Menu Item</a>
            <br>
            <a href="{% url 'sales_history' %}" class="big-card">Sales History</a>
            <br>
            
            
        </div>
        
    </div>
</body>
</html>

restaurant/templates/restaurant/configure.html
{% extends 'restaurant/admin_layout.html' %}

{% block title %} Admin Home {% endblock %}

{% block content %}

    <div id="main-content">
        <div id="configure-form">
            <h2>Configuration</h2>

            <form method="post" action="{% url 'configure' %}" enctype="multipart/form-data">

                {% csrf_token %}
                
                <label for="restaurant_name"><b>Restaurant Name:</b></label>
                <input type="text" name="restaurant_name" id="restaurant_name" required>

                <br>
                
                <label for="logo"><b>Restaurant Logo:</b></label>
                <input type="file" name="logo" id="logo" required>
                <br>
                
                <button type="submit"><b>Change Configuration</b></button>
            
            </form>

        
        
        </div>
    </div>

{% endblock %}

restaurant/templates/restaurant/index.html
{% extends 'restaurant/layout.html' %}

{% block content %}
    <div id="menu">
        <h1>MENU</h1>
        {%for item in menu_items %}
            <div class="item">
                <h2 id="food">{{item.item_name}}</h2>
                <p>
                    <h4>Description </h4>
                    <h5 style="text-wrap: wrap; width:80%;"> {{item.description}}</h5>
                </p>
                <img align='right' src="{{item.image.url}}" class = "menu_image">
                <br>
                <h2 id="food">{{item.price}} BDT</h2>
                <br>
            {%if user.is_authenticated %}
                <form action = "{% url 'add_to_cart' item_id=item.id %}" method = "post">
                    {% csrf_token %}
                    <button type = 'submit' class="button add-to-cart-btn">ADD TO CART</button>
                </form>
            {% else %}
              <form action = "{% url 'login' %}" method ="get">
                {% csrf_token %}
                <button type = 'submit' class="button add-to-cart-btn">LOGIN TO ADD TO CART</button>
              </form>
            {%endif%}
                
            </div>
        {%endfor%}
    </div>

    <div id="cart">
        {%if not placed %}
        <h2>CART</h2>

  
    <form action = "{% url 'confirm_order' %}" method = "post">

        {%for item in order_items%}
        
            <div class="cart-item">
                <div class="item-details">
                    <h3>{{item.menu_item.item_name}}</h3>
                    <p>Price: BDT {{item.menu_item.price}}</p>
                </div>
                <div class="item-actions">
                    <div class="quantity">
                        <label for="quantity">Quantity:</label>
                        <input type="number" id="quantity" name="quantity" min="1" class = "quantity-box" value="{{item.quantity}}" readonly>
                    </div>
                    
                </div>
                <a href="{%url 'remove_item' item.id%}">X</a>

                
            </div>

        {%endfor%}
            <br>
      
        
        
            {% csrf_token %}
            <input type = "hidden" name = "order_id" value = {{order.id}}>
            <button type = 'submit' class="button add-to-cart-btn">Confirm Order</button>
        </form>    

        <br>
    {%if confirm%}
        <h2>SUBTOTAL: {{order.grand_total}}</h2>
<br>
<div class="shipping-details">
    <h3 id="shipping-details-title">Shipping Details</h3>
    
    <form method = "post" id="shippingForm" style="max-width: 400px; margin: 0 auto; padding: 20px; background-color: #f2f2f2;; border-radius: 8px; " action= "{%url 'place_order'%}">
    {% csrf_token %}
        <input type = "hidden" name = "order_id" value = {{order.id}}>
    
        <label for="houseNo">House No:</label>
        <input class = 'address-info' type="text" id="houseNo" name="houseNo"  required>
    
        <label for="flatNo" style="display: block; margin-bottom: 5px; color: #333;">Flat No:</label>
        <input class = 'address-info' type ="text" id="flatNo" name="flatNo"  required>
    
        <label for="streetAddress" style="display: block; margin-bottom: 5px; color: #333;">Street Address:</label>
        <input class = 'address-info' type="text" id="streetAddress" name="streetAddress"  required>

        <label for="additional" style="display: block; margin-bottom: 5px; color: #333;">Additional Instructions :</label>
        <input class = 'address-info' type="text" id="additional" name="additional">
        
    
        <label for="paymentMethod" id = "payment-label"><b>Payment method:</b></label>
        <select id="paymentMethod" name="paymentMethod">
            <option value="cash">Cash</option>
            <option value="card">Card</option>
            <option value="bkash">bKash</option>
            <option value="nagad">Nagad</option>
    
        </select>
<br><br>

        <input type="submit" value="PLACE ORDER" style="background-color: #4caf50; color: #fff; padding: 10px; cursor: pointer; border: none; border-radius: 5px;">
    </form>
    
</div>
             




   
    {%endif%}

{%else%}
        <h3>Your order is being processed. </h3>
{% endif %}
</div>

{% endblock %}

restaurant/templates/restaurant/layout.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{{restaurant.title}}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'restaurant/styles.css' %}">
</head>
<body>
    <div id="header">
        <img src = "{{restaurant.logo.url}}" id = "main-logo">
        {%if restaurant.title %}
            <h1>{{restaurant.title}} e-Restaurant</h1>
        {%else%}
            <h1>Restaurant Ordering System</h1>
            {{restaurant.title}}
        {%endif%}
        <a href="{% url 'index' %}">Home</a> |
        {% if user.is_authenticated %}
        Signed in as {{ user.username }} | <a href="{% url 'logout' %}">Logout</a>

            {% if user.is_admin %} 
                <button class="panel-button"  onclick="window.location.href='{% url 'admin_home' %}'">Admin Panel</button>
            {%else%}
                 <button class="panel-button"  onclick="window.location.href='{% url 'user_orders' %}'">My Orders</button>
            {% endif %}

        {% else %}
            <a href="{% url 'login' %}">Login</a> |
            <a href="{% url 'register' %}">Register</a>
        {% endif %}
        
 
    </div>

    <div id="main-content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

restaurant/templates/restaurant/login.html
{% extends 'restaurant/layout.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div id="main-content">
        <div id="login-form">
            <h2>Login</h2>
            <form method="post" action="{% url 'login' %}">
                {% csrf_token %}
                
                <label for="id_username">Username:</label>
                <input type="text" name="username" id="id_username" required>
                <br>
                
                <label for="id_password">Password:</label>
                <input type="password" name="password" id="id_password" required>
                <br>
                
                <button type="submit">Login</button>
            </form>

            {% if message %}
            <div style="background-color: #e74c3c; color: white; padding: 10px; border-radius: 5px; margin-top: 10px;">
                {{ message }}
            </div>
            
         {% endif %}
        </div>
    </div>
{% endblock %}

restaurant/templates/restaurant/manage_menu.html
{% extends 'restaurant/admin_layout.html' %}



{% block content %}
<div id = "menu-container">
<h1>MANAGE MENU</h1>
<a href="{%url 'add_item'%}" class="add-button"> + Add New Menu Item</a>

<br style = "margin: 10px;">
    <div id="menu">
        
        
        {%for item in menu_items %}
       
            <form method = "post" action = "{%url 'update_item'%}" enctype="multipart/form-data">
                {% csrf_token %}
                <input type = "hidden" value = "{{item.id}}" name = "item_id">
                <div class="item">
                    <h3><label for ="food" >Item Name:</label>  <a href="{%url 'remove_menu_item' item.id%}">X</a>
                        <input type = 'text' value = "{{item.item_name}}" id="food" name = "item_name" accept="image/*">
                    </h3>
                    
                    <p>
                        <h3><label for = "description">Description: </label>
                            <br style = "margin: 20px;">
                        <textarea type = 'text'  id="description" name = "item_description"> {{item.description}}</textarea>

                        
                        </h3>
                    </p>
                <div id = "price_and_image">
                    <div class = "price_image_div">
                        <h3 id="food">PRICE: </h3>
                        <input type="number" value = "{{item.price}}" name = "item_price">
                        <button type = 'submit' class="button update-btn">UPDATE ITEM</button>
                    </div>
                    <div class = "price_image_div">
                        <label for="fileInput" class="upload-button">
                            <img align='right' src="{{item.image.url}}" class = "menu_image" >
                            <span>Change Image</span>
                        </label>
                        <input type="file" id="fileInput" style="display: none;" name = "item_img">
                        <br style = "margin: 20px;">
                        
                
                    </div>
                    
                    <br>
                
            </div>
                    <br>
                    <br style = "margin: 20px;">
                    
                
                
                
            
                    
                </div>
            </form>
        {%endfor%}
    </div>
</div>

{% endblock %}

restaurant/templates/restaurant/register.html
{% extends 'restaurant/layout.html' %}

{% block title %}Register{% endblock %}

{% block content %}
    <div id="main-content">
        <div id="register-form">
            <h2>Register</h2>
            
            <form method="post" action="{% url 'register' %}">
                {% csrf_token %}
                
                <label for="id_username">Username:</label>
                <input type="text" name="username" id="id_username" required>
                <br>
                
                <label for="id_name">First Name:</label>
                <input type="text" name="first_name" id="id_name" required>
                <br>
                
                <label for="id_name">Last Name:</label>
                <input type="text" name="last_name" id="id_name" required>
                <br>

                <label for="id_email">Email:</label>
                <input type="email" name="email" id="id_email" required>
                <br>
                
                <label for="id_password">Password:</label>
                <input type="password" name="password" id="id_password" required>
                <br>
                
                <label for="id_confirm_password">Confirm Password:</label>
                <input type="password" name="confirmation" id="id_confirm_password" required>
                <br>
                
                <label for="id_phone_number">Phone Number:</label>
                <input type="text" name="phone_number" id="id_phone_number" required>
                <br>
                
                <button type="submit">Register</button>
            </form>

            {% if message %}
            <div style="background-color: #e74c3c; color: white; padding: 10px; border-radius: 5px; margin-top: 10px;">
                {{ message }}
            </div>
            
         {% endif %}

        </div>
    </div>
{% endblock %}